### PR TITLE
Update README.md with go v1.10 requirement

### PR DESCRIPTION
**Pull request by phillipj**
Because of the [go v1.10 requirement](https://github.com/gopasspw/gopass#installation) of gopass, this project cannot be built with go v1.9 anymore.

This is obvious when trying to build with v1.9:

```
$ go build
# github.com/camptocamp/terraform-provider-pass/vendor/github.com/gopasspw/gopass/pkg/store/secret
vendor/github.com/gopasspw/gopass/pkg/store/secret/kv.go:64:10: undefined: strings.Builder
vendor/github.com/gopasspw/gopass/pkg/store/secret/secret.go:67:10: undefined: strings.Builder

...
```

This is fixed by upgrading to 1.10.4 (current latest of 1.10).

### CODE REVIEW

**Comment by mcanevet** [comment]
@phillipj this PR is not merge-able could you please rebase?

**Comment by phillipj** [comment]
Sure thing ✔️
